/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author User
 */
public class ThreadState extends javax.swing.JPanel
{

    /**
     * Creates new form ThreadState
     */
    public ThreadState(String name)
    {
        initComponents();
        lbPanel.setText(name);
        
    }
    
    public void setThreadRunning()
    {
        lbPanel.setBackground(Color.green);
    }
    
    public void setThreadWaiting()
    {
        lbPanel.setBackground(Color.red);
    }

    public void setThreadSleeping()
    {
        lbPanel.setBackground(Color.orange);
    }
    
    public void setThreadFinished()
    {
        lbPanel.setBackground(Color.MAGENTA);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbPanel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lbPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPanel.setOpaque(true);
        add(lbPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbPanel;
    // End of variables declaration//GEN-END:variables
}
